server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopappdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true # khi chương trình chạy thì hiển thị các câu lệnh sql
    hibernate:
      ddl-auto: none # lúc tạo entity sẽ không tự tạo table trong db. vì khi đội dev nhiều, mỗi người thay đổi 1 chút thì rất nguy hiêm
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # driver để kết nối với cơ sở dữ liệu
        format_sql: true # format câu lệnh sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1